FROM python:3.6.8-alpine3.8 as base
FROM base as builder
RUN apk --no-cache --update-cache add gcc python python-dev py-pip build-base wget
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip install pipenv
RUN mkdir -p /src/ngsi-timeseries-api
COPY Pipfile /src/ngsi-timeseries-api/Pipfile
COPY Pipfile.lock /src/ngsi-timeseries-api/Pipfile.lock
WORKDIR /src/ngsi-timeseries-api
# XXX use of --system is required to get all the paths right in the final docker image
# it has the disadvantage of not updating Pipfile.lock, though, so that the latter must be
# up-to-date when building this dockerfile
RUN pipenv install --system

FROM base
RUN apk --no-cache add curl
COPY --from=builder /usr/local /usr/local
COPY . /src/ngsi-timeseries-api/
WORKDIR /src/ngsi-timeseries-api/src
ENV QL_CORS_ALLOWED_ORIGIN ""

CMD python app.py
