version: 2.1

jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t orchestracities/quantumleap:$CIRCLE_BRANCH .
      - run: cd timescale-container && docker build -t orchestracities/quantumleap-db-setup:$CIRCLE_BRANCH .
  test_translators:
    docker:
      - image: cimg/python:3.8.3
    steps:
      - checkout
      - run:
          command: pipenv shell

workflows:
  main:
    jobs:
      - build
      - test_translators
