version: 2.1

jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t orchestracities/quantumleap:$CIRCLE_BRANCH .
      - run: cd timescale-container && docker build -t orchestracities/quantumleap-db-setup:$CIRCLE_BRANCH .
  test_translators:
    docker:
      - image: cimg/python:3.8.3
    steps:
      - checkout
      - run:
          command: |
            source deps.env
            LH=`( /sbin/ifconfig ens4 | grep 'inet' | cut -d: -f2 | awk '{ print $1}' ) 2> /dev/null`
            if [ -z "$LH" ]
            then
            # Aliasing so that notifications from orion container reach dev localhost
              LH=192.0.0.1
              sudo ifconfig lo0 alias $LH
            fi

            export ORION_HOST=$LH
            export MONGO_HOST=$LH

            export QL_HOST=$LH
            export CRATE_HOST=$LH
            export POSTGRES_HOST=$LH

            export REDIS_HOST=$LH

            [[ "$LH" != "192.0.0.1" ]] || pipenv shell

workflows:
  main:
    jobs:
      - build
      - test_translators
