version: 2.1

jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t orchestracities/quantumleap:$CIRCLE_BRANCH .
      - run: cd timescale-container && docker build -t orchestracities/quantumleap-db-setup:$CIRCLE_BRANCH .


workflows:
  main:
    jobs:
      - build
