version: 2.1

jobs: 
  build:
    machine: true
    steps:
      - checkout
      - restore_docker_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Dockerfile" }}
      - run: docker build -t orchestracities/quantumleap:$CIRCLE_BRANCH .
      - save_python_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Dockerfile" }}
          paths:
            - " /var/lib/docker/"
  test_translators:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: "Switch to Python v3.8.5"
          command: |
            pyenv versions
            pyenv global 3.8.5
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8
      - restore_python_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo add-apt-repository universe
            sudo apt install python3-pip
            pip install pipenv
            pipenv install --dev
      - save_python_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8"
      - restore_docker_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Dockerfile" }}
      - run:
          command: |
              export SHELL=no
              source setup_dev_env.sh
              echo "CrateDB"
              echo $CRATE_VERSION
              #sh run_tests.sh

workflows:
  main:
    jobs:
      - build
      - test_translators
