version: '3'

services:

  orion:
    extends:
      file: docker-compose-common.yml
      service: orion
    depends_on:
      - mongo

  mongo:
    extends:
      file: docker-compose-common.yml
      service: mongo

  crate:
    extends:
      file: docker-compose-common.yml
      service: crate

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis

  dashboard:
    extends:
      file: docker-compose-common.yml
      service: dashboard

  timescale:
    extends:
      file: docker-compose-common.yml
      service: timescale

  quantumleap-db-setup:
    extends:
      file: docker-compose-common.yml
      service: quantumleap-db-setup
    depends_on:
      - timescale

  quantumleap:
    extends:
      file: docker-compose-common.yml
      service: quantumleap
    depends_on:
#      - crate
      - timescale
      - redis
    networks:
      - wqtests
    environment:
      - WQ_OFFLOAD_WORK=true
#      - WQ_MAX_RETRIES=3
      - QL_DEFAULT_DB=timescale
      - POSTGRES_HOST=timescale
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=quantumleap
      - POSTGRES_DB_USER=quantumleap
      - POSTGRES_DB_PASS=*
      - POSTGRES_USE_SSL=False
      - CACHE_QUERIES=True

  quantumleap-wq:
    extends:
      file: docker-compose-common.yml
      service: quantumleap-wq

volumes:
  mongodata:
  cratedata:
  redisdata:

networks:
    default:
    wqtests:
