# Convert the following to png using http://www.gravizo.com/#converter.
@startuml;
skinparam componentStyle uml2

!define ICONURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/master/dist
!includeurl ICONURL/common.puml
!includeurl ICONURL/fiware.puml

FIWARE(cb,"Orion \nContext Broker",component)

package "IoT Layer" {
    FIWARE(iota,"IoT Agent",component)
}

iota -up-> "2" cb
[Client] "1" -up-> cb
[Cache]

package "QuantumLeap" {
	FIWARE(api,"API",component)
	FIWARE(reporter,"Reporter",component)
	FIWARE(translator,"Translator",component)
	FIWARE(geocoder,"Geocoder",component)
	FIWARE(worker,"Worker",component)
	api <-down-> reporter
  worker <-up-> translator
	reporter <-right-> translator
	reporter <-down-> geocoder
	reporter <-down-> [Cache]
}
cb "3" -down-> api
[Client] "4" <-down-> api
worker <-down-> [Cache]
geocoder <-down-> [Cache]
[OSM] <-down- geocoder
[DB Cluster] <-left- translator
[Cache] <-left- translator
[Dashboard] "5" -down-> [DB Cluster]
api <-right- [Dashboard]

@enduml
